# Generated by Django 4.2.7 on 2026-01-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_app', '0002_passwordresetpin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
