# Generated by Django 4.2.7 on 2026-01-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_app', '0006_alter_contactinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
