# Generated by Django 4.2 on 2026-01-30 20:15

from django.db import migrations, models
import money_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('money_app', '0008_alter_faq_options_faq_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='order',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, validators=[money_app.models.validate_phone_number]),
        ),
    ]
